# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Zett"
license = "GNUGPLV3"
licenselink = "https://www.gnu.org/licenses/gpl-3.0.html"
description = "Note-taking tool based on Zettelkästen"
homepage = "@todo"
tags = ["@todo"]
features = ["@todo"]
min_version = "0.0.1"
assetsDir = "assets"

[author]
  name = "Fran Acién"
  homepage = "https://github.com/acien101"
