baseurl: "https://example.com"
languageCode: en-EN
defaultContentLanguage: en
title: Your site's title
theme: Zett
uglyURLS: true
publishDir: public
pygmentsUseClasses: true
googleAnalytics: Your google analytics number
# assetDir = "themes/zettels/assets"

outputs:
  home: ["HTML", "RSS", "JSON"]

params:
  favicon: "favicon.ico"
  todofeat: false # false to deactivate the todo notes feature
  todoCoefficients:
    near: 12
    blocking: 8
    highp: 6
    medp: 3
    lowp: 2
    started: 4
    old: 2
    bloqued: -5

markup.goldmark.renderer:
  unsafe: true
